### ISSUE TITLE
CSS Snapping?

### ISSUE THREAD

**Issue by iccowan** [1000ship/react-scroll-motion#10]
I noticed that it appears a `scroll-snap-align` attribute is being assigned to each `ScrollPage`, but I can't seem to figure out how to get snapping to work. Is there some extra CSS that should be added? If not, is there any way this could be easily added (maybe an option to turn it on or off)? Thank you!

**Comment by iccowan** [comment]
Actually, I couldn't figure this out so I went ahead and implemented a solution that works directly with the package (see #11).

**Comment by 1000ship** [comment]
I checked your PR, Thanks! :)
