### ISSUE TITLE
To everyone who report issues

### ISSUE THREAD

**Issue by 1000ship** [1000ship/react-scroll-motion#13]
Thank you guys to all react-scroll-motion users :)
I'm always looking your issues and reactions. And I can't believe it grows up like this much.
Unfortunately, I have to concentrate on my business. So can't update just moment.
I hope I can fix all of things and wanna make it better.
I'll come back here asap tho.

Thanks you guys again. Happy new year and see you!

**Comment by cpu-byte** [comment]
Fantastic package my friend. Hope your business goes well, good luck! 🍀
