### ISSUE TITLE
Typescript error while using batch

### ISSUE THREAD

**Issue by namratasaun** [1000ship/react-scroll-motion#17]
whenever I try to use batch in my react typescript project, I get error about number of arguments.
Hence proposing a solution in this pull request
https://github.com/1000ship/react-scroll-motion/pull/16
@1000ship please consider this

**Comment by 1000ship** [comment]
Thanks again :)
I merged your code and I'm gonna deploy it

**Comment by nsaun-dq** [comment]
Thanks a lot for being so kind. Kudos to this great library.
