### ISSUE TITLE
Possibility to animate on some given path?

### ISSUE THREAD

**Issue by JakubSapko** [1000ship/react-scroll-motion#24]
Hi there,
is there a possibility to animate something on custom path on scroll? Let's say I have a box which renders at the left side of the viewport after mounting and with scroll I want to animate it alongside a sine wave up to the right side of the viewport. Is this possible?

**Comment by 1000ship** [comment]
Yes, it possible.
You can make custom animation

Check this out, please

https://github.com/1000ship/react-scroll-motion#make-custom-animation
