### ISSUE TITLE
Module not found: Can't resolve 'react-scroll-motion'

### ISSUE THREAD

**Issue by sobad321** [1000ship/react-scroll-motion#26]
<a href="https://ibb.co/yX0p0ML"><img src="https://i.ibb.co/nbrBrVh/Screenshot-2022-06-09-065503.png" alt="Screenshot-2022-06-09-065503" border="0"></a>

Why ? I tried everything to install it but it can't

**Comment by 1000ship** [comment]
Sorry, I can't find out what is the problem in that context..
