### ISSUE TITLE
Potential typo?

### ISSUE THREAD

**Issue by zakjanzi** [1000ship/react-scroll-motion#45]
```
<ScrollContainer snap="mandatory">
  <ScrollPage>
    <Animator animation={batch(Fade(), Sticky(), MoveOut(0, -200))}>
      <MediumText>Let't me show you scroll animation 😀</MediumText>
    </Animator>
  </ScrollPage>
<ScrollContainer>
```

This snippet was copied from the markup example [here](https://github.com/1000ship/react-scroll-motion/blob/HEAD/_readme/docs.md)

Should the last `<ScrollContainer>` tag be `</ScrollContainer>` instead?

**Comment by 1000ship** [comment]
Oh, it's my mistake.
Thanks for letting me know. I'll fix it
