### ISSUE TITLE
Hi, I think it is not working in Next.js 13 app routing version

### ISSUE THREAD

**Issue by nidevelop** [1000ship/react-scroll-motion#46]
I know it works in Next.js pages router project. I checked the example code and I saw it works!

But I tryed many times in Next.js 13 verson, app router project, it doesn't work at all. 

The error says like this, Even it doesn't work with only the ScrollContainer.

Or did I worng? I import that code in directory '(root)/app/page.js'

Pls show update the new example on Next.js 13 app routing version.

Or let me know how can I use it in Next.js 13 app routing.

ps. it works when I change the page CSR with code 'use client' on top.
That means this module is not working on SSR 😥
ps2. I tried to import all the components as dynamic import too. It didn't work 😥

error :
Unhandled Runtime Error
Error: (0 , react_1.createContext) is not a function

**Comment by levipadre** [comment]
Same  problem here

**Comment by 1000ship** [comment]
Hi, first of all, thank you for using my module :)

I know the updates of NextJS v13+, and I've utilized with that version also.
For my `react-scroll-motion` module, the root (`ScrollContainer`) components needs to use Javascript for handling children-components' styles. So it must be CSR mode, it means by 'use client' must be set.

By the way, you don't have to make your page as the CSR mode.
So, I just updated my code by adding `"use client"` on the `<ScrollContainer/>` component, which is the root component of my module.

Can you reinstall with `react-scroll-motion@0.3.3` and try it again?

Sorry for checking it lately.
If you're still addressing this issue, I hope you doing well ;)

**Comment by 1000ship** [comment]
Here's example with NextJS v14
https://github.com/1000ship/nextjs-14-react-scroll-motion
