### ISSUE TITLE
Despite Installing and Using Version 0.3.3, I am Experiencing Issues with CSR Mode

### ISSUE THREAD

**Issue by Lee-Dongwook** [1000ship/react-scroll-motion#48]
Hello, I am a university student learning front-end using NextJS.
First of all, thank you for sharing your valuable library.
Looking at the list of issues posted by others, I understand that you released version 0.3.3 two days ago, modified to be compatible with NextJS 13 or higher.
However, while reinstalling and using the version, I found the same error as before.
I raised this issue because I was wondering if I was using it incorrectly.
I would appreciate your reply!

**Comment by Lee-Dongwook** [comment]
앗 제가 처음에 한국분이신지 모르고 영어로 이슈 올렸네요😅  시간 편하실 때 답변 주시면 감사하겠습니다!

**Comment by 1000ship** [comment]
NextJS 13버전부터 달라진게 있긴한데 “use client" 만으론 뭔가 해결이 안되는것 같군요.
오늘 한 번 저도 추가해보고, 업데이트 해보겠습니다.
늦은 답변 죄송합니다 ;)

**Comment by 1000ship** [comment]
NextJS 14버전이긴하지만, 동작테스트해보았습니다.
"use client" 사용 시, dynamic 으로 모듈을 로드할 필요가 없군요!

https://github.com/1000ship/nextjs-14-react-scroll-motion
